language: python

notifications:
  email:
    on_success: change
    on_failure: change

os:
- linux

python:
  - "2.7"

# - "3.4" # fix map for this
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
# command to run tests
script:
- coverage run travis_tests.py


after_success:
- codecov

skip_cleanup: true
